server:
  port: 4000

spring:
  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

    sentinel:
      transport:
        dashboard: localhost:8080
        #默认是8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719
        #将流控规则配置进nacos保存

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


feign:
  hystrix:
    enabled: false
  sentinel:
     enabled: true

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'


