server:
  port: 4003

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    alibaba:
      seata:
        tx-service-group: my_test_tx_group



  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

